version: "3.8"

services:
    localstack:
        container_name: "localstack"
        image: localstack/localstack
        ports:
            - "4566:4566" # LocalStack Gateway
            - "4510-4559:4510-4559" # external services port range
    mongodb:
        container_name: "mongodb"
        image: mongo
        ports:
            - "27017:27017"
