FROM node:18-alpine AS deps

WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json yarn.lock ./
RUN yarn config set network-timeout 600000 -g && yarn install --frozen-lockfile

FROM node:18-alpine AS builder

ARG MONGODB_URI=${MONGODB_URI}
ENV MONGODB_URI=${MONGODB_URI}

ARG PAYLOAD_SECRET=${PAYLOAD_SECRET}
ENV PAYLOAD_SECRET=${PAYLOAD_SECRET}

ARG PAYLOAD_CONFIG_PATH=${PAYLOAD_CONFIG_PATH}
ENV PAYLOAD_CONFIG_PATH=${PAYLOAD_CONFIG_PATH}

ARG INIT_ADMIN_EMAIL=${INIT_ADMIN_EMAIL}
ENV INIT_ADMIN_EMAIL=${INIT_ADMIN_EMAIL}

ARG INIT_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD}
ENV INIT_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD}

ARG SEED_TOKEN=${SEED_TOKEN}
ENV SEED_TOKEN=${SEED_TOKEN}

ARG APP_URL=${APP_URL}
ENV APP_URL=${APP_URL}

ARG SES_ACCESS_KEY=${SES_ACCESS_KEY}
ENV SES_ACCESS_KEY=${SES_ACCESS_KEY}

ARG SES_SECRET_ACCESS_KEY=${SES_SECRET_ACCESS_KEY}
ENV SES_SECRET_ACCESS_KEY=${SES_SECRET_ACCESS_KEY}

ARG SES_REGION=${SES_REGION}
ENV SES_REGION=${SES_REGION}

ARG S3_REGION=${S3_REGION}
ENV S3_REGION=${S3_REGION}

ARG S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
ENV S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}

ARG S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
ENV S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

ARG S3_ENDPOINT=${S3_ENDPOINT}
ENV S3_ENDPOINT=${S3_ENDPOINT}

ARG S3_BUCKET=${S3_BUCKET}
ENV S3_BUCKET=${S3_BUCKET}

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
RUN yarn build

FROM node:18-alpine as runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/package.json ./
COPY --from=builder /app/yarn.lock ./
USER nextjs
EXPOSE 3000
ENV PORT 3000
CMD ["yarn", "start"]
